### ISSUE TITLE
Zatikon crashes on Wayland session

### ISSUE THREAD

**Issue by CredibleOpossum** [zatikon/zatikon#47]
X11 sessions work fine, attempting to launch a wayland session creates an exception:
```
flatpak run com.chroniclogic.Zatikon
Extra args:  --
Java args: 
Other args: 
2023-12-13 20:56:36 [main] leo.client.Client.main()
INFO: Attempting normal login
Exception in thread "main" java.awt.HeadlessException: 
No X11 DISPLAY variable was set,
but this program performed an operation which requires it.
    at java.desktop/java.awt.GraphicsEnvironment.checkHeadless(GraphicsEnvironment.java:166)
    at java.desktop/java.awt.Window.<init>(Window.java:553)
    at java.desktop/java.awt.Frame.<init>(Frame.java:428)
    at java.desktop/java.awt.Frame.<init>(Frame.java:393)
    at leo.client.ClientLoginDialog.<init>(ClientLoginDialog.java:64)
    at leo.client.Client.main(Client.java:182)
```

Current workaround is to change permissions to use X11 without possibility of Wayland.
![image](https://github.com/zatikon/zatikon/assets/60998830/27306757-e050-4aee-9b75-4898d4761ced)

**Comment by lukky513** [comment]
From brief reading on the topic a while ago, it seems that Wayland is not supported for AWT/Swing, and I suppose it will likely remain so for a good while. I will restore X11 requirement in the Flatpak, and I guess we might come back to it when we have a chance of changing the graphics system entirely.

**Comment by lukky513** [comment]
Not an issue in the latest version. Proper Wayland support would be its own ticket, but that has to wait for either graphics rewrite, or for JDK to catch up.
